"""desc added to box model

Revision ID: 4c83c950e366
Revises: ce90b32eb897
Create Date: 2024-05-31 20:03:28.007403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c83c950e366'
down_revision: Union[str, None] = 'ce90b32eb897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'desc')
    # ### end Alembic commands ###
